In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[10, 64],
       [19, 72],
       [49,  7],
       [10, 84],
       [79,  7],
       [57, 80],
       [79, 68],
       [23,  5],
       [85, 91],
       [65, 84]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/Users/spencer/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[ 0.        ,  0.68604651],
       [ 0.12      ,  0.77906977],
       [ 0.52      ,  0.02325581],
       [ 0.        ,  0.91860465],
       [ 0.92      ,  0.02325581],
       [ 0.62666667,  0.87209302],
       [ 0.92      ,  0.73255814],
       [ 0.17333333,  0.        ],
       [ 1.        ,  1.        ],
       [ 0.73333333,  0.91860465]])

In [9]:
import pandas as pd

In [11]:
mydata=np.random.randint(0,101,(50,4))

In [12]:
mydata

array([[ 37,  97,  56,  84],
       [ 36,  15,  44,   5],
       [ 76,  25,  91,  11],
       [ 27,  17,  26,   6],
       [ 65,  12,  54,  87],
       [ 43,  87,   1,  86],
       [ 48,  22,   6,   4],
       [ 66,  21,  94,   2],
       [ 91,  55,  26,  85],
       [ 23,  61,  30,  43],
       [ 17,  25,   1,  82],
       [ 72,  18,   4,  71],
       [ 24,   3,  95,  36],
       [ 70,  36,  78,  31],
       [ 55,  30,  84,  20],
       [ 12,  49,  73,  32],
       [ 80,  99,  31,  94],
       [  1,  78,  51,  14],
       [ 32,   5,  70,  14],
       [ 40,  58,  58,  83],
       [  0,  69,  42,  98],
       [ 65,  85,  84,  90],
       [ 98,  35,  66,  65],
       [  7,  29,  22,  21],
       [ 70,  40,  46,  88],
       [ 52,  46,  60,  12],
       [ 27,  58,  57,  63],
       [ 29,   4,  84, 100],
       [ 21,  81,  13,   3],
       [ 31,  34,  49,  81],
       [ 26,  54,  13,   2],
       [ 58,   4,  94,  70],
       [ 11,  16,  92,  93],
       [  5,  82,  18,  69],
       [ 75,  

In [20]:
df = pd.DataFrame(data=mydata, columns = ['f1', 'f2', 'f3', 'label'])

In [21]:
df

f1  f2  f3  label
0   37  97  56     84
1   36  15  44      5
2   76  25  91     11
3   27  17  26      6
4   65  12  54     87
5   43  87   1     86
6   48  22   6      4
7   66  21  94      2
8   91  55  26     85
9   23  61  30     43
10  17  25   1     82
11  72  18   4     71
12  24   3  95     36
13  70  36  78     31
14  55  30  84     20
15  12  49  73     32
16  80  99  31     94
17   1  78  51     14
18  32   5  70     14
19  40  58  58     83
20   0  69  42     98
21  65  85  84     90
22  98  35  66     65
23   7  29  22     21
24  70  40  46     88
25  52  46  60     12
26  27  58  57     63
27  29   4  84    100
28  21  81  13      3
29  31  34  49     81
30  26  54  13      2
31  58   4  94     70
32  11  16  92     93
33   5  82  18     69
34  75  68  66     42
35  45  90  27     25
36  25  60  44     34
37  26  95  61      6
38  94  77  83     41
39  72  40   0     79
40  79  24  70     69
41   4  24  97     57
42  41  30  34     85
43  32  79  94     74
44  85  76  20     20
45  20  95  27     12
46  69  65  15     95
47  24  67  36      2
48  96  47  16     53
49  82  71   2     21

In [22]:
X = df[['f1','f2', 'f3']]

In [23]:
X

f1  f2  f3
0   37  97  56
1   36  15  44
2   76  25  91
3   27  17  26
4   65  12  54
5   43  87   1
6   48  22   6
7   66  21  94
8   91  55  26
9   23  61  30
10  17  25   1
11  72  18   4
12  24   3  95
13  70  36  78
14  55  30  84
15  12  49  73
16  80  99  31
17   1  78  51
18  32   5  70
19  40  58  58
20   0  69  42
21  65  85  84
22  98  35  66
23   7  29  22
24  70  40  46
25  52  46  60
26  27  58  57
27  29   4  84
28  21  81  13
29  31  34  49
30  26  54  13
31  58   4  94
32  11  16  92
33   5  82  18
34  75  68  66
35  45  90  27
36  25  60  44
37  26  95  61
38  94  77  83
39  72  40   0
40  79  24  70
41   4  24  97
42  41  30  34
43  32  79  94
44  85  76  20
45  20  95  27
46  69  65  15
47  24  67  36
48  96  47  16
49  82  71   2

In [24]:
y = df['label']

In [25]:
y

0      84
1       5
2      11
3       6
4      87
5      86
6       4
7       2
8      85
9      43
10     82
11     71
12     36
13     31
14     20
15     32
16     94
17     14
18     14
19     83
20     98
21     90
22     65
23     21
24     88
25     12
26     63
27    100
28      3
29     81
30      2
31     70
32     93
33     69
34     42
35     25
36     34
37      6
38     41
39     79
40     69
41     57
42     85
43     74
44     20
45     12
46     95
47      2
48     53
49     21
Name: label, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [28]:
X_train.shape

(35, 3)

In [30]:
X_test.shape

(15, 3)