In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.3.0


In [4]:
hello = tf.constant("Hello ") #a constant is the most basic type of tensor

In [5]:
world = tf.constant("World")

In [6]:
type(hello) #hello is a tensor object

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess: #"with" automatically opens and closes the session
    result = sess.run(hello + world)

In [11]:
print(result) #b represents a bytes literal in Python

b'Hello World'


In [12]:
a = tf.constant(10)

In [13]:
b = tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [17]:
a + b #task is actually executed since it's not run inside of a session

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [16]:
a + b #TF is keeps track of how many times this operation was executed

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [19]:
result

30

In [20]:
const = tf.constant(10)

In [22]:
fill_mat = tf.fill((4,4),10) #gives 4x4 matrix filled with 10s

In [24]:
myzeros = tf.zeros((4,4))

In [25]:
myones = tf.ones((4,4))

In [28]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0) #random normal distribution

In [29]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [31]:
myzeros #waiting to be run in a session 

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [32]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [33]:
sess = tf.InteractiveSession() #interactive session that is active across multiple cells i.e. no need for "with" statement; mostly only useful for a notebook environment

In [38]:
for op in my_ops:
    print(sess.run(op)) #could replace "sess.run(op)" with "op.eval()" for same results
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.94925022 -0.1409228   0.63877261 -2.01453948]
 [-0.08561103 -0.10219218  1.90836287 -0.7097131 ]
 [ 0.80104327 -0.36415443 -1.78915668  0.79704094]
 [ 0.15210254 -0.42210832  0.28399155  1.75724065]]


[[ 0.5972954   0.05940771  0.29543102  0.96494567]
 [ 0.82756269  0.15647173  0.19094968  0.91204536]
 [ 0.77107561  0.38699389  0.97766399  0.6320678 ]
 [ 0.2779783   0.67361999  0.41696227  0.14772654]]




In [39]:
a = tf.constant([[1,2],  #2x2 matrix ; rows x columns
                [3,4]])

In [40]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [42]:
b = tf.constant([[10],[100]]) #2x1 matrix

In [43]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [44]:
result = tf.matmul(a,b) #multiply the matricies a and b

In [45]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [46]:
result.eval()

array([[210],
       [430]], dtype=int32)