In [2]:
from sklearn.datasets import load_wine

In [3]:
wine_data = load_wine()

In [4]:
type(wine_data)

sklearn.utils.Bunch

In [5]:
wine_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [6]:
print(wine_data['DESCR'])

Wine Data Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- 1) Alcohol
 		- 2) Malic acid
 		- 3) Ash
		- 4) Alcalinity of ash  
 		- 5) Magnesium
		- 6) Total phenols
 		- 7) Flavanoids
 		- 8) Nonflavanoid phenols
 		- 9) Proanthocyanins
		- 10)Color intensity
 		- 11)Hue
 		- 12)OD280/OD315 of diluted wines
 		- 13)Proline
        	- class:
                - class_0
                - class_1
                - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash: 

In [8]:
feat_data = wine_data['data']

In [13]:
feat_data

array([[  1.42300000e+01,   1.71000000e+00,   2.43000000e+00, ...,
          1.04000000e+00,   3.92000000e+00,   1.06500000e+03],
       [  1.32000000e+01,   1.78000000e+00,   2.14000000e+00, ...,
          1.05000000e+00,   3.40000000e+00,   1.05000000e+03],
       [  1.31600000e+01,   2.36000000e+00,   2.67000000e+00, ...,
          1.03000000e+00,   3.17000000e+00,   1.18500000e+03],
       ..., 
       [  1.32700000e+01,   4.28000000e+00,   2.26000000e+00, ...,
          5.90000000e-01,   1.56000000e+00,   8.35000000e+02],
       [  1.31700000e+01,   2.59000000e+00,   2.37000000e+00, ...,
          6.00000000e-01,   1.62000000e+00,   8.40000000e+02],
       [  1.41300000e+01,   4.10000000e+00,   2.74000000e+00, ...,
          6.10000000e-01,   1.60000000e+00,   5.60000000e+02]])

In [15]:
labels = wine_data['target']

In [16]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
from sklearn.model_selection import train_test_split

In [27]:
train_test_split(feat_data,labels)

[array([[  1.30500000e+01,   3.86000000e+00,   2.32000000e+00, ...,
           8.40000000e-01,   2.01000000e+00,   5.15000000e+02],
        [  1.30700000e+01,   1.50000000e+00,   2.10000000e+00, ...,
           1.18000000e+00,   2.69000000e+00,   1.02000000e+03],
        [  1.23700000e+01,   1.17000000e+00,   1.92000000e+00, ...,
           1.12000000e+00,   3.48000000e+00,   5.10000000e+02],
        ..., 
        [  1.27700000e+01,   2.39000000e+00,   2.28000000e+00, ...,
           5.70000000e-01,   1.63000000e+00,   4.70000000e+02],
        [  1.34100000e+01,   3.84000000e+00,   2.12000000e+00, ...,
           9.10000000e-01,   3.00000000e+00,   1.03500000e+03],
        [  1.16100000e+01,   1.35000000e+00,   2.70000000e+00, ...,
           9.60000000e-01,   3.26000000e+00,   6.80000000e+02]]),
 array([[  1.23300000e+01,   9.90000000e-01,   1.95000000e+00,
           1.48000000e+01,   1.36000000e+02,   1.90000000e+00,
           1.85000000e+00,   3.50000000e-01,   2.76000000e+00,
   

In [20]:
x_train, x_test, y_train, y_test = train_test_split(feat_data,labels,test_size=0.3,random_state=101)

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler = MinMaxScaler()

In [22]:
scaled_x_train = scaler.fit_transform(x_train)

In [26]:
scaled_x_test = scaler.transform(x_test) #don't fit since we don't know what the test data will be

In [28]:
import tensorflow as tf

In [29]:
from tensorflow import estimator

In [31]:
x_train.shape

(124, 13)

In [32]:
feat_cols = [tf.feature_column.numeric_column('x',shape=[13])]

In [33]:
deep_model = estimator.DNNClassifier(hidden_units=[13,13,13],feature_columns=feat_cols,n_classes=3,
                                     optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.01))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/yh/ftwq6yz50j970hfx8k08g4880000gn/T/tmp0nu470az', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}


In [34]:
input_fn = estimator.inputs.numpy_input_fn(x={'x':scaled_x_train},y=y_train,shuffle=True,batch_size=10,
                                          num_epochs=5)

In [35]:
deep_model.train(input_fn=input_fn,steps=500)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/yh/ftwq6yz50j970hfx8k08g4880000gn/T/tmp0nu470az/model.ckpt.
INFO:tensorflow:loss = 10.8091, step = 1
INFO:tensorflow:Saving checkpoints for 62 into /var/folders/yh/ftwq6yz50j970hfx8k08g4880000gn/T/tmp0nu470az/model.ckpt.
INFO:tensorflow:Loss for final step: 2.78032.


In [36]:
input_fn_eval = estimator.inputs.numpy_input_fn(x={'x':scaled_x_test},shuffle=False)

In [37]:
preds = list(deep_model.predict(input_fn=input_fn_eval))

INFO:tensorflow:Restoring parameters from /var/folders/yh/ftwq6yz50j970hfx8k08g4880000gn/T/tmp0nu470az/model.ckpt-62


In [40]:
preds

[{'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logits': array([ 0.92551291,  0.07867309, -2.07217479], dtype=float32),
  'probabilities': array([ 0.67628336,  0.28996852,  0.03374811], dtype=float32)},
 {'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logits': array([ 0.98835528,  0.20429853, -2.57240391], dtype=float32),
  'probabilities': array([ 0.67341548,  0.30744791,  0.01913661], dtype=float32)},
 {'class_ids': array([2]),
  'classes': array([b'2'], dtype=object),
  'logits': array([-1.48677039, -0.67599446,  1.89429641], dtype=float32),
  'probabilities': array([ 0.03062621,  0.06889834,  0.9004755 ], dtype=float32)},
 {'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logits': array([ 2.01977229, -0.77288574, -2.47853017], dtype=float32),
  'probabilities': array([ 0.9325    ,  0.05712324,  0.01037674], dtype=float32)},
 {'class_ids': array([2]),
  'classes': array([b'2'], dtype=object),
  'logits': array([-1.9

In [42]:
predictions = [p['class_ids'][0] for p in preds]

In [45]:
predictions

[0,
 0,
 2,
 0,
 2,
 1,
 2,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 0,
 1,
 1,
 0]

In [48]:
from sklearn.metrics import classification_report

In [49]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        19
          1       1.00      0.91      0.95        22
          2       0.87      1.00      0.93        13

avg / total       0.97      0.96      0.96        54

