In [1]:
from sklearn.datasets import load_wine

In [2]:
wine_data = load_wine()

In [3]:
type(wine_data)

sklearn.utils.Bunch

In [4]:
wine_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [5]:
print(wine_data['DESCR'])

Wine Data Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- 1) Alcohol
 		- 2) Malic acid
 		- 3) Ash
		- 4) Alcalinity of ash  
 		- 5) Magnesium
		- 6) Total phenols
 		- 7) Flavanoids
 		- 8) Nonflavanoid phenols
 		- 9) Proanthocyanins
		- 10)Color intensity
 		- 11)Hue
 		- 12)OD280/OD315 of diluted wines
 		- 13)Proline
        	- class:
                - class_0
                - class_1
                - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash: 

In [6]:
feat_data = wine_data['data']

In [7]:
feat_data

array([[  1.42300000e+01,   1.71000000e+00,   2.43000000e+00, ...,
          1.04000000e+00,   3.92000000e+00,   1.06500000e+03],
       [  1.32000000e+01,   1.78000000e+00,   2.14000000e+00, ...,
          1.05000000e+00,   3.40000000e+00,   1.05000000e+03],
       [  1.31600000e+01,   2.36000000e+00,   2.67000000e+00, ...,
          1.03000000e+00,   3.17000000e+00,   1.18500000e+03],
       ..., 
       [  1.32700000e+01,   4.28000000e+00,   2.26000000e+00, ...,
          5.90000000e-01,   1.56000000e+00,   8.35000000e+02],
       [  1.31700000e+01,   2.59000000e+00,   2.37000000e+00, ...,
          6.00000000e-01,   1.62000000e+00,   8.40000000e+02],
       [  1.41300000e+01,   4.10000000e+00,   2.74000000e+00, ...,
          6.10000000e-01,   1.60000000e+00,   5.60000000e+02]])

In [8]:
labels = wine_data['target']

In [9]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_test_split(feat_data,labels)

[array([[  1.34800000e+01,   1.67000000e+00,   2.64000000e+00, ...,
           5.70000000e-01,   1.78000000e+00,   6.20000000e+02],
        [  1.18400000e+01,   8.90000000e-01,   2.58000000e+00, ...,
           7.90000000e-01,   3.08000000e+00,   5.20000000e+02],
        [  1.32400000e+01,   2.59000000e+00,   2.87000000e+00, ...,
           1.04000000e+00,   2.93000000e+00,   7.35000000e+02],
        ..., 
        [  1.43800000e+01,   1.87000000e+00,   2.38000000e+00, ...,
           1.20000000e+00,   3.00000000e+00,   1.54700000e+03],
        [  1.23300000e+01,   1.10000000e+00,   2.28000000e+00, ...,
           1.25000000e+00,   1.67000000e+00,   6.80000000e+02],
        [  1.26400000e+01,   1.36000000e+00,   2.02000000e+00, ...,
           9.80000000e-01,   1.59000000e+00,   4.50000000e+02]]),
 array([[  1.29300000e+01,   2.81000000e+00,   2.70000000e+00,
           2.10000000e+01,   9.60000000e+01,   1.54000000e+00,
           5.00000000e-01,   5.30000000e-01,   7.50000000e-01,
   

In [12]:
x_train, x_test, y_train, y_test = train_test_split(feat_data,labels,test_size=0.3,random_state=101)

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler = MinMaxScaler()

In [15]:
scaled_x_train = scaler.fit_transform(x_train)

In [16]:
scaled_x_test = scaler.transform(x_test) #don't fit since we don't know what the test data will be

### Layers API Section

In [17]:
import tensorflow as tf

In [18]:
import pandas as pd

In [19]:
onehot_y_train = pd.get_dummies(y_train).as_matrix()

In [20]:
onehot_y_train

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0,

In [21]:
onehot_y_test = pd.get_dummies(y_test).as_matrix()

In [22]:
num_feat = 13
num_hidden1 = 13 #number of neurons in first hidden layer
num_hidden2 = 13
num_outputs = 3

In [23]:
learning_rate = 0.01

In [24]:
from tensorflow.contrib.layers import fully_connected

In [25]:
x = tf.placeholder(tf.float32,shape=[None,num_feat])

In [26]:
y_true = tf.placeholder(tf.float32,shape=[None,3])

In [27]:
actf = tf.nn.relu #activation function

In [28]:
hidden1 = fully_connected(x,num_hidden1,activation_fn=actf) # "layers" API

In [29]:
hidden2 = fully_connected(hidden1,num_hidden2,activation_fn=actf) # "layers" API

In [30]:
output = fully_connected(hidden2,num_outputs) # "layers" API

In [31]:
loss = tf.losses.softmax_cross_entropy(onehot_labels=y_true,logits=output)

In [32]:
optimizer = tf.train.AdamOptimizer(learning_rate)

In [33]:
train = optimizer.minimize(loss)

In [34]:
init = tf.global_variables_initializer()

In [55]:
training_steps = 1000

In [56]:
with tf.Session() as sess:
    sess.run(init)
    for i in range(training_steps):
        sess.run(train,feed_dict={x:scaled_x_train,y_true:onehot_y_train})
        
    logits = output.eval(feed_dict={x:scaled_x_test})
    preds = tf.argmax(logits,axis=1)
    results = preds.eval()
    print("finished")

finished


In [57]:
from sklearn.metrics import classification_report

In [58]:
print(classification_report(results,y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        19
          1       1.00      1.00      1.00        22
          2       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        54

